apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: promrub-api-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: promrub-api-secret        # name of the k8s Secret to be created
  data:
  - secretKey: ERP_EMAIL
    remoteRef:
      key: initial-secret
      property: ERP_EMAIL
