envAlias: development
domainScb: scb-api.promrub-dev.prom.co.th
domainKonga: konga.promrub-dev.prom.co.th
domainKong: api.promrub-dev.prom.co.th
domainPub: dev.promrub.com
domainPgAdmin: pgweb.promptrub-dev.prom.co.th
domainPaymentUI: dev-payment-channel.promrub.com
domainPaymentAPI: dev-single-payment-api.promrub.com
domainPaymentReactUI: finance-dev.prom.co.th

promrub-scb:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

promrub-api:
  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: ASPNETCORE_ENVIRONMENT
        value: "Development"

      - name: HTTP_PORTS
        value: "80"

      - name: IsDev
        value: "true"

      - name: PostgreSQL_Host
        value: "postgresql-scb" #Use the same SCB host

      - name: PostgreSQL_Database
        value: "promrub"

      - name: PostgreSQL_User
        value: "postgres"

      - name: PostgreSQL_Password
        valueFrom:
          secretKeyRef:
            name: scb-postgres-secret #Use the same SCB host
            key: adminPasswordKey
            optional: false

      - name: PaymentUrl
        value: "https://dev-payment-channel.promrub.com"

      - name: SCBServicesUrl
        value: "https://api.promrub.prom.co.th/scb/"

      - name: SCBGenerateQRUrl
        value: "v1/QRGenerate/CreateQR30Async"

      - name: ERP_EMAIL
        valueFrom:
          secretKeyRef:
            name: promrub-api-secret
            key: adminPasswordKey
            optional: false

      - name: QR_Action
        value: "https://sales1-dev.prom.co.th/"
