envAlias: production
domainScb: scb-api.promrub.prom.co.th
domainKonga: konga.promrub.prom.co.th
domainKong: api.promrub.prom.co.th
domainPub: promrub.com
domainPgAdmin: pgweb.promptrub.prom.co.th
domainPaymentUI: payment-channel.promrub.com
domainPaymentAPI: single-payment-api.promrub.com

promrub-scb:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

promrub-api:
  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: ASPNETCORE_ENVIRONMENT
        value: "Production"

      - name: IsDev
        value: "false"

      - name: PostgreSQL_Host
        value: "postgresql-scb" #Use the same SCB host

      - name: PostgreSQL_Database
        value: "promrub"

      - name: PostgreSQL_User
        value: "postgres"

      - name: PostgreSQL_Password
        valueFrom:
          secretKeyRef:
            name: scb-postgres-secret #Use the same SCB host
            key: adminPasswordKey
            optional: false

      - name: PaymentUrl
        value: "https://payment-channel.promrub.com"

      - name: SCBServicesUrl
        value: "https://api.promrub.prom.co.th/scb/"

      - name: SCBGenerateQRUrl
        value: "v1/QRGenerate/CreateQR30Async"
